# Generated by Django 3.2.9 on 2021-11-16 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cityx',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
