# Generated by Django 3.2.9 on 2021-11-16 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_cityx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cityx',
        ),
    ]
