# Generated by Django 3.2.9 on 2021-11-16 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
