# Generated by Django 3.2.9 on 2021-11-14 04:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211114_1011'),
        ('shop', '0002_auto_20211114_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='addedon',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='qty',
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('qty', models.IntegerField(blank=True, null=True)),
                ('addedon', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.customer')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='cartitems',
            field=models.ManyToManyField(null=True, to='shop.CartItem'),
        ),
    ]
