# Generated by Django 3.2.9 on 2021-11-14 05:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cartitems',
            field=models.ManyToManyField(to='shop.CartItem'),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('products', models.ManyToManyField(to='shop.Product')),
            ],
        ),
    ]
